--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/IvanCraft623/fakeblocks
build-by-default: true
branches:
- main
projects:
  fakeblocks:
    path: ""
    model: virion
    type: library
    libs:
      - src: Muqsit/SimplePacketHandler/SimplePacketHandler
        version: ^0.1.0
...
